@startuml
actor User
User -> TaskController: GET /task/getTaskById
activate TaskController
TaskController -> TaskService: findTask(id)
activate TaskService
TaskService -> TaskRepository: findById(id)
activate TaskRepository
TaskRepository -> TaskService: Task
deactivate TaskRepository
TaskService -> TaskController: Task
deactivate TaskService
TaskController -> User: ResponseEntity<Object>
deactivate TaskController
@enduml
